# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
	desc "Push a new beta build to TestFlight"
  	lane :beta do
  		ensure_git_status_clean
  		match(type: "appstore")
  		increment_build_number
  		commit_version_bump(message: "Bump to version: #{get_version_number}(b#{get_build_number})")
		add_git_tag(tag: "v#{get_version_number}/b#{get_build_number}")
  		push_to_git_remote(remote: "NAS")
    	gym(export_method: "app-store")
    	pilot
    	notification(title: "Application published on TestFlight")
  	end

  	lane :test do
  	desc "Lane used for experimentations"
  		increment_build_number
		add_git_tag(tag: "v#{get_version_number}/b#{get_build_number}")
	end
end
